apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myweb-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/bhusal1/yamls.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
   
  syncPolicy
    syncOptions:
    - CreatNamespace=true


    automated:
      selfHeal: true
      prune: true
